#!/usr/bin/env python3
import json
import sys
import requests
from typing import Dict, Any

# Advanced Task: Exposing AnythingLLM RAG as an MCP Server
# This allows Multica / OpenClaw agents to query the Vector DB dynamically.

ANYTHING_LLM_URL = "http://localhost:3001"
API_KEY = "YOUR_ANYTHING_LLM_API_KEY"
WORKSPACE_SLUG = "team-mandy-docs"

def handle_tools_list() -> Dict[str, Any]:
    """Expose the available tools to the MCP Client."""
    return {
        "jsonrpc": "2.0",
        "id": 1,
        "result": {
            "tools": [
                {
                    "name": "query_rag_database",
                    "description": "Searches the internal corporate knowledge base via AnythingLLM. Use this to find company policies, project details, and technical documentation.",
                    "inputSchema": {
                        "type": "object",
                        "properties": {
                            "query": {
                                "type": "string",
                                "description": "The specific question to ask the database."
                            }
                        },
                        "required": ["query"]
                    }
                }
            ]
        }
    }

def handle_query_rag(query: str) -> Dict[str, Any]:
    """Execute the vector search against AnythingLLM."""
    url = f"{ANYTHING_LLM_URL}/api/v1/workspace/{WORKSPACE_SLUG}/chat"
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json"
    }
    payload = {
        "message": query,
        "mode": "chat"
    }
    
    try:
        response = requests.post(url, json=payload, headers=headers)
        response.raise_for_status()
        data = response.json()
        
        # Extract the text response generated by the RAG system
        answer = data.get("textResponse", "No response found.")
        return {
            "content": [
                {
                    "type": "text",
                    "text": answer
                }
            ]
        }
    except Exception as e:
        return {
            "content": [
                {
                    "type": "text",
                    "text": f"Error querying database: {str(e)}"
                }
            ],
            "isError": True
        }

def main():
    """Main JSON-RPC loop for stdio MCP Server"""
    for line in sys.stdin:
        try:
            req = json.loads(line)
            method = req.get("method")
            
            if method == "tools/list":
                print(json.dumps(handle_tools_list()))
            elif method == "tools/call":
                tool_name = req.get("params", {}).get("name")
                args = req.get("params", {}).get("arguments", {})
                
                if tool_name == "query_rag_database":
                    res = handle_query_rag(args.get("query", ""))
                    print(json.dumps({"jsonrpc": "2.0", "id": req.get("id"), "result": res}))
            
            sys.stdout.flush()
        except json.JSONDecodeError:
            continue

if __name__ == "__main__":
    main()
